  s3BucketName1: "prakash-terraform-app-states"
  s3Path1: "/cloudformation-templates/"
  templateName1: "ec2-template.yaml"
  templatePath1: "./cloudFormationTemplates/"
  paramPath1: "./paramFiles"
  paramPathFolder1: "paramFiles"
  stackName1: "cf-webserver-ec2"
  instanceName1: "webserv-tomcat"
  instanceFolderNamePosition1: 1